# Generated by Django 3.2.9 on 2021-11-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=255)),
                ('a_password', models.CharField(max_length=16)),
            ],
        ),
    ]
