
# Generated by Django 3.2.9 on 2021-12-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_addservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicesmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=100)),
                ('phn', models.IntegerField()),
                ('distric', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('s_license', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
# Generated by Django 3.2.9 on 2021-12-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_addservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicesmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=100)),
                ('phn', models.IntegerField()),
                ('distric', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('s_license', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]

