
# Generated by Django 3.2.9 on 2021-12-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_auto_20211203_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]

# Generated by Django 3.2.9 on 2021-12-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_auto_20211203_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]

