# Generated by Django 3.2.9 on 2021-12-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_alter_servicesmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=255)),
                ('u_email', models.EmailField(max_length=254, verbose_name='')),
                ('u_phn', models.IntegerField()),
                ('u_address', models.CharField(max_length=255)),
                ('u_password', models.CharField(max_length=16)),
                ('u_confpass', models.CharField(max_length=16)),
            ],
        ),
    ]
