# Generated by Django 3.2.3 on 2021-12-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0007_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.servicesmodel')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.addservice')),
            ],
        ),
    ]
